apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  namespace: marketplace
  labels:
    app: php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: marketplace-php:latest
        ports:
        - containerPort: 9000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: marketplace-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: marketplace-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: marketplace-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: marketplace-config
              key: DB_PASSWORD
        volumeMounts:
        - name: app-storage
          mountPath: /var/www/html
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: app-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
  namespace: marketplace
spec:
  selector:
    app: php
  ports:
  - port: 9000
    targetPort: 9000
  type: ClusterIP
